# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://demostudent18.github.io'
baseurl:             '/til'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Demo Student
  url:               https://demostudent18.com
  email:             demostudent18@firstdraft.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version:             1.1.0
